### ISSUE TITLE
Graceful failures

### ISSUE THREAD

**Issue by jonocarroll** [mpadge/stellar#12]
Add graceful failure routes, e.g. in `stars`: `user = NULL`, `phrase = NULL`. I'm happy to do this.

Alternatively, have useful defaults. Related to #7.

**Comment by mpadge** [comment]
Only exposed fn at present is
```
stars (phrase = "", user = NULL, language = NULL, newest_first = TRUE)
```
although no real param checks have been implemented. doing that would help a lot! Thanks!

**Comment by mpadge** [comment]
Great work @jonocarroll - happy to close this now?

**Comment by jonocarroll** [comment]
Yeah, I think it's pretty clean now re: unexpected failures.
