### ISSUE TITLE
default phrase behaviour

### ISSUE THREAD

**Issue by MHenderson** [mpadge/stellar#20]
Hi,

The documentation for `stars` says:

phrase | Text string to search for. Defaults to returning all starred repositories from the specified user
-- | --

But this doesn't seem to be the case.

``` r
library(stellar)
#> 
#> Attaching package: 'stellar'
#> The following object is masked from 'package:graphics':
#> 
#>     stars

stars(user = "MHenderson", phrase = "stars")
#> [34m[1] [32mropenscilabs/stellar[39m[49m :
#> [34mSearch your github stars in R[39m[49m
#> 
#> choose a repository to open, or anything else to exit:

stars(user = "MHenderson")
#> That text does not appear to describe any starred repositories
```

Best wishes,
Matthew

**Comment by jonocarroll** [comment]
Thank you! That's my bad for the implementation of the default. Until I patch this (very soon) you can explicitly set `phrase = NULL` to achieve this (I think).

**Comment by jonocarroll** [comment]
Hopefully working now. Thanks again!

**Comment by MHenderson** [comment]
Yes, it does. Thanks!
