### ISSUE TITLE
switch on travis

### ISSUE THREAD

**Issue by mpadge** [mpadge/stellar#3]
@maelle I don't have the necessary authority to switch on travis for ropenscilabs - Could you please do that? Thanks! :smiley:

**Comment by maelle** [comment]
Done https://travis-ci.org/ropenscilabs/stellar

**Comment by mpadge** [comment]
I just saw that and though, huh? So quick? On a Saturday morning? You're amazing. Now get out and enjoy the sunshine like I'm about to! Thank you

**Comment by maelle** [comment]
Lol early mornings mean I have already been outside 😂
